import Head from 'next/head'
import {BsFillMenuButtonFill} from 'react-icons/bs'
import Link from 'next/link'
import { useState } from 'react'


export default function Home() {
  return (
    <div >
      <Head>
        <title>ROY, Developer Coder Designer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className='w-screen h-screen flex'>
        <div className="left-screen w-1/2 relative bg-[url('/pic1.jpeg')] bg-cover bg-center">
         
          <div className='overlay absolute w-full h-full bg-black opacity-70'></div>
        </div>
        <div className='right-screen w-1/2 flex items-center justify-center'>
            <p className='text-center'>
              <span className='text-3xl font-extrabold'>Hi</span>
              <div>
              <span className='text-2xl font-semibold'>I am</span>
              <span className='text-5xl font-extrabold mx-1'>ROY</span>
              </div>
              <span className='text-lg font-bold'>CODER</span>
            </p>
        </div>
        <MenuList />
      </div>
      
      

    </div>
  )
}

const MenuList = () => {
  const [showMenu , setToggleMenu] = useState(false)
  return(
    <div className='absolute bottom-4 right-4 flex flex-col items-end '>
        <ul className={`menulist w-48 mb-2 border rounded-sm ${!showMenu && 'hidden'}`}>
            <Link href="/myproject"><li className='cursor-pointer hover:bg-black hover:text-white hover:font-semibold p-2'>My Project</li></Link>
            <li className='cursor-pointer hover:bg-black hover:text-white hover:font-semibold p-2'>My Skills</li>
            <li className='cursor-pointer hover:bg-black hover:text-white hover:font-semibold p-2'>My Academics</li>
        </ul>
      <div onClick={() => {showMenu ? setToggleMenu(false) : setToggleMenu(true)}} className='w-9 h-9 animate-pulse bg-black text-white rounded-full text-center shadow-lg flex items-center justify-center'><BsFillMenuButtonFill size={20}/></div>
    
    </div>
    
  )
}