import Head from 'next/head'
import { Navbar } from '../components/Navbar'

export default function MyProject() {
  return (
    <div >
      <Head>
        <title>ROY, Developer Coder Designer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <div className='flex w-screen'>
        <div className='flex items-center justify-center h-[calc(100vh_-_2.5rem)] bg-gray-50 w-1/4'>
          <p className='flex flex-col'>
            <span className=''>Comapnies I worked for</span>
            <span className='font-extrabold uppercase text-lg '>Accenture</span>
            <span className='font-extrabold text-2xl leading-4'>My Concerto</span>
          </p>
        </div>
        <div className='h-full m-auto'>
          <ProjectCard />
        </div>
      </div>
    </div>
  )
}


const ProjectCard = () => {
  return(
    <div className='container card w-2/3 m-auto'>
        <div className='card-head h-1/3 flex mb-2'>
          <img src='/pic1.jpeg' className='aspect-video h-56 '/>
          <p className='mx-2 flex items-center'>
          <span className='mr-2 text-lg font-extrabold'>
            Durations
          </span>
          <span className=''>
            <span className='font-extrabold text-2xl'>2020</span>
            <div className='h-2 w-8 m-auto bg-black'></div>
            <span className='font-extrabold text-2xl'>2022</span>
          </span>
        </p>
        </div>
        <div className='card-body'>
        <label className='py-2 font-bold text-xl'>React JS Developer - Asset Management Portal UI/UX</label>
        
        <div>
        <div className='font-bold text-lg my-2'>Desccription</div>
        <p className='mx-4 text-base text-gray-700'>
          • Developed rich responsive reusable UI components with React JS for
          Contribution Portal<br />
          • Used CSS library BootStrap 4 for stylings<br />
          • Used ES6 Scripts to build a highly responsive SPA<br />
          • UsedWebpack and Bubble to build react applications<br />
          • Worked with Redux for state management.<br />
          • Extensively using chrome developer tools for tracking and debugging.<br />
          • Used Azure Devops CI-CD Pipeline for continuous deployment. bugs
          and resolving issues.
        </p>
        </div>
        </div>
        <div className='my-2'>
          <label className='font-bold text-lg'>Tech Stack</label>
          <div className='flex mt-2 items-center border border-black w-fit p-2 rounded-sm'>
            <div className='w-8 h-8 bg-black rounded-full'></div>
            <label className='ml-2 font-bold t'>React JS</label>
          </div>
        </div>
        
    </div>
  )
}
